### PR TITLE
Delivery pipeline for cc_java

### PR DESCRIPTION
**Pull request by huynt1979**

### CODE REVIEW

**Comment by huynt1979** [comment]
This PR has passed 'Verify' and is ready for review and approval!
  Use: '@delivery approve' when code review is complete.

**Comment by majormoses** [comment]
@delivery approve

**Comment by huynt1979** [comment]
@majormoses He he... you are not set up for this Chef Delivery yet. That's why you can't approve. Only me....

**Comment by huynt1979** [comment]
@cc-delivery approve

**Comment by huynt1979** [comment]
@delivery approve

**Comment by huynt1979** [comment]
Change: 0e4b6024-a8cf-4d67-975e-171849daf185 approved by: @huynt1979

**Comment by huynt1979** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Comment by huynt1979** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Comment by huynt1979** [comment]
This PR has passed 'Acceptance' and is ready to be delivered!
  Use: '@delivery deliver' when validated in acceptance.

**Pull request merged**
